/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl4.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl4.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl4.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getTerminalAccess().getAlternatives(), "rule__Terminal__Alternatives");
			builder.put(grammarAccess.getSumAccess().getGroup(), "rule__Sum__Group__0");
			builder.put(grammarAccess.getSumAccess().getGroup_1(), "rule__Sum__Group_1__0");
			builder.put(grammarAccess.getSumAccess().getGroup_1_0(), "rule__Sum__Group_1_0__0");
			builder.put(grammarAccess.getSumAccess().getGroup_1_0_0(), "rule__Sum__Group_1_0_0__0");
			builder.put(grammarAccess.getMulAccess().getGroup(), "rule__Mul__Group__0");
			builder.put(grammarAccess.getMulAccess().getGroup_1(), "rule__Mul__Group_1__0");
			builder.put(grammarAccess.getMulAccess().getGroup_1_0(), "rule__Mul__Group_1_0__0");
			builder.put(grammarAccess.getMulAccess().getGroup_1_0_0(), "rule__Mul__Group_1_0_0__0");
			builder.put(grammarAccess.getTerminalAccess().getGroup_0(), "rule__Terminal__Group_0__0");
			builder.put(grammarAccess.getNegAccess().getGroup(), "rule__Neg__Group__0");
			builder.put(grammarAccess.getLiteralAccess().getGroup(), "rule__Literal__Group__0");
			builder.put(grammarAccess.getSumAccess().getRhsAssignment_1_1(), "rule__Sum__RhsAssignment_1_1");
			builder.put(grammarAccess.getMulAccess().getRhsAssignment_1_1(), "rule__Mul__RhsAssignment_1_1");
			builder.put(grammarAccess.getNegAccess().getExpAssignment_2(), "rule__Neg__ExpAssignment_2");
			builder.put(grammarAccess.getLiteralAccess().getValueAssignment_1(), "rule__Literal__ValueAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
