site_name: Alex Language
remote_name: manuelleduc
theme: readthedocs
nav:
  - 'index.md'
  - 'installation.md'
  - 'getting-started.md'
  - 'revisitor.md'
markdown_extensions:
  - codehilite:
      linenums: true
