site_name: Alex Language
remote_name: diverse-project
theme: readthedocs
nav:
  - 'index.md'
  - 'installation.md'
  - 'getting-started.md'
  - 'extension.md'
  - 'composition.md'
  - 'revisitor.md'
  - 'publications.md'
  - 'about.md'
markdown_extensions:
  - codehilite:
      linenums: true
  - toc:
      baselevel: 1
      permalink: "#"
