/*
 * generated by Xtext 2.15.0
 */
package fr.mleduc.lang.boa.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class BoaUiModule extends AbstractBoaUiModule {
}
