/*
 * generated by Xtext 2.14.0
 */
package fr.mleduc.lang.boa.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBoaScopeProvider extends DelegatingScopeProvider {
}
