/*
 * generated by Xtext 2.14.0
 */
package alex.xtext.parser.antlr;

import alex.xtext.parser.antlr.internal.InternalAlexParser;
import alex.xtext.services.AlexGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class AlexParser extends AbstractAntlrParser {

	@Inject
	private AlexGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAlexParser createParser(XtextTokenStream stream) {
		return new InternalAlexParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "AlexRoot";
	}

	public AlexGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AlexGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
