/*
 * generated by Xtext 2.12.0
 */
package alex.xtext.ide

import alex.xtext.AlexRuntimeModule
import alex.xtext.AlexStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class AlexIdeSetup extends AlexStandaloneSetup {

	override createInjector() {
		return Guice.createInjector(Modules2.mixin(new AlexRuntimeModule, new AlexIdeModule))
	}

}
