/*
 * generated by Xtext 2.14.0
 */
package fr.inria.diverse.alex.xtext.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractAlexScopeProvider extends XbaseBatchScopeProvider {
}
