/*
 * generated by Xtext 2.14.0
 */
package boa.xtext.serializer;

import boa.xtext.services.BoaGrammarAccess;
import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class BoaSyntacticSequencer extends AbstractSyntacticSequencer {

	protected BoaGrammarAccess grammarAccess;
	protected AbstractElementAlias match_File_SemicolonSemicolonKeyword_1_1_2_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (BoaGrammarAccess) access;
		match_File_SemicolonSemicolonKeyword_1_1_2_q = new TokenAlias(false, true, grammarAccess.getFileAccess().getSemicolonSemicolonKeyword_1_1_2());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_File_SemicolonSemicolonKeyword_1_1_2_q.equals(syntax))
				emit_File_SemicolonSemicolonKeyword_1_1_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ';;'?
	 *
	 * This ambiguous syntax occurs at:
	 *     commands+=TopLevelCmd (ambiguity) ';;' commands+=TopLevelCmd
	 *     commands+=TopLevelCmd (ambiguity) (rule end)
	 */
	protected void emit_File_SemicolonSemicolonKeyword_1_1_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
