/*
 * generated by Xtext 2.14.0
 */
package alex.xtext.ui.tests;

import alex.xtext.ui.internal.XtextActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class AlexUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("alex.xtext.Alex");
	}

}
