/*
 * generated by Xtext 2.14.0
 */
package alex.xtext.ui.editor;

import org.eclipse.xtext.xbase.ui.editor.XbaseEditor;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass.
 */
public class AlexEditor extends XbaseEditor {
}
