/*
 * generated by Xtext 2.14.0
 */
package calc.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCalcScopeProvider extends DelegatingScopeProvider {
}
