/*
 * generated by Xtext 2.14.0
 */
package calc.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CalcStandaloneSetup extends CalcStandaloneSetupGenerated {

	def static void doSetup() {
		new CalcStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
