/*
 * generated by Xtext 2.14.0
 */
package calc.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class CalcRuntimeModule extends AbstractCalcRuntimeModule {
}
