/*
 * generated by Xtext 2.10.0
 */
package fr.inria.diverse.alex.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AlexStandaloneSetup extends AlexStandaloneSetupGenerated {

	def static void doSetup() {
		new AlexStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
