/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl4.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.mydsl4.ui.internal.Mydsl4Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(Mydsl4Activator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		Mydsl4Activator activator = Mydsl4Activator.getInstance();
		return activator != null ? activator.getInjector(Mydsl4Activator.ORG_XTEXT_EXAMPLE_MYDSL4_MYDSL) : null;
	}

}
