/*
 * generated by Xtext 2.14.0
 */
package calc.xtext.ide

import calc.xtext.CalcRuntimeModule
import calc.xtext.CalcStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class CalcIdeSetup extends CalcStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new CalcRuntimeModule, new CalcIdeModule))
	}
	
}
