/*
 * generated by Xtext 2.15.0
 */
package fr.mleduc.lang.boa.ide

import com.google.inject.Guice
import fr.mleduc.lang.boa.BoaRuntimeModule
import fr.mleduc.lang.boa.BoaStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class BoaIdeSetup extends BoaStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new BoaRuntimeModule, new BoaIdeModule))
	}
	
}
