/**
 * generated by Xtext 2.14.0
 */
package fr.inria.diverse.alex.xtext.alex;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Class</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.alex.xtext.alex.AlexClass#isAbstract <em>Abstract</em>}</li>
 *   <li>{@link fr.inria.diverse.alex.xtext.alex.AlexClass#getName <em>Name</em>}</li>
 *   <li>{@link fr.inria.diverse.alex.xtext.alex.AlexClass#getMutables <em>Mutables</em>}</li>
 *   <li>{@link fr.inria.diverse.alex.xtext.alex.AlexClass#getMethods <em>Methods</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.alex.xtext.alex.AlexPackage#getAlexClass()
 * @model
 * @generated
 */
public interface AlexClass extends EObject
{
  /**
   * Returns the value of the '<em><b>Abstract</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Abstract</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Abstract</em>' attribute.
   * @see #setAbstract(boolean)
   * @see fr.inria.diverse.alex.xtext.alex.AlexPackage#getAlexClass_Abstract()
   * @model
   * @generated
   */
  boolean isAbstract();

  /**
   * Sets the value of the '{@link fr.inria.diverse.alex.xtext.alex.AlexClass#isAbstract <em>Abstract</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Abstract</em>' attribute.
   * @see #isAbstract()
   * @generated
   */
  void setAbstract(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.inria.diverse.alex.xtext.alex.AlexPackage#getAlexClass_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.inria.diverse.alex.xtext.alex.AlexClass#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Mutables</b></em>' containment reference list.
   * The list contents are of type {@link fr.inria.diverse.alex.xtext.alex.MutableRef}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mutables</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mutables</em>' containment reference list.
   * @see fr.inria.diverse.alex.xtext.alex.AlexPackage#getAlexClass_Mutables()
   * @model containment="true"
   * @generated
   */
  EList<MutableRef> getMutables();

  /**
   * Returns the value of the '<em><b>Methods</b></em>' containment reference list.
   * The list contents are of type {@link fr.inria.diverse.alex.xtext.alex.AlexMethod}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Methods</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Methods</em>' containment reference list.
   * @see fr.inria.diverse.alex.xtext.alex.AlexPackage#getAlexClass_Methods()
   * @model containment="true"
   * @generated
   */
  EList<AlexMethod> getMethods();

} // AlexClass
