/**
 * generated by Xtext 2.14.0
 */
package fr.inria.diverse.alex.xtext.alex;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Import</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.alex.xtext.alex.AlexImport#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.alex.xtext.alex.AlexPackage#getAlexImport()
 * @model
 * @generated
 */
public interface AlexImport extends EObject
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ref</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(AlexRoot)
   * @see fr.inria.diverse.alex.xtext.alex.AlexPackage#getAlexImport_Ref()
   * @model
   * @generated
   */
  AlexRoot getRef();

  /**
   * Sets the value of the '{@link fr.inria.diverse.alex.xtext.alex.AlexImport#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(AlexRoot value);

} // AlexImport
