/**
 * generated by Xtext 2.14.0
 */
package fr.inria.diverse.alex.xtext.alex;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.xtext.xtype.XImportSection;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Root</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.alex.xtext.alex.AlexRoot#getName <em>Name</em>}</li>
 *   <li>{@link fr.inria.diverse.alex.xtext.alex.AlexRoot#getCompileTargets <em>Compile Targets</em>}</li>
 *   <li>{@link fr.inria.diverse.alex.xtext.alex.AlexRoot#getJavaImports <em>Java Imports</em>}</li>
 *   <li>{@link fr.inria.diverse.alex.xtext.alex.AlexRoot#getEcoreImport <em>Ecore Import</em>}</li>
 *   <li>{@link fr.inria.diverse.alex.xtext.alex.AlexRoot#getAlexImports <em>Alex Imports</em>}</li>
 *   <li>{@link fr.inria.diverse.alex.xtext.alex.AlexRoot#getClasses <em>Classes</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.alex.xtext.alex.AlexPackage#getAlexRoot()
 * @model
 * @generated
 */
public interface AlexRoot extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.inria.diverse.alex.xtext.alex.AlexPackage#getAlexRoot_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.inria.diverse.alex.xtext.alex.AlexRoot#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Compile Targets</b></em>' containment reference list.
   * The list contents are of type {@link fr.inria.diverse.alex.xtext.alex.CompileTarget}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Compile Targets</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Compile Targets</em>' containment reference list.
   * @see fr.inria.diverse.alex.xtext.alex.AlexPackage#getAlexRoot_CompileTargets()
   * @model containment="true"
   * @generated
   */
  EList<CompileTarget> getCompileTargets();

  /**
   * Returns the value of the '<em><b>Java Imports</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Java Imports</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Java Imports</em>' containment reference.
   * @see #setJavaImports(XImportSection)
   * @see fr.inria.diverse.alex.xtext.alex.AlexPackage#getAlexRoot_JavaImports()
   * @model containment="true"
   * @generated
   */
  XImportSection getJavaImports();

  /**
   * Sets the value of the '{@link fr.inria.diverse.alex.xtext.alex.AlexRoot#getJavaImports <em>Java Imports</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Java Imports</em>' containment reference.
   * @see #getJavaImports()
   * @generated
   */
  void setJavaImports(XImportSection value);

  /**
   * Returns the value of the '<em><b>Ecore Import</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ecore Import</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ecore Import</em>' containment reference.
   * @see #setEcoreImport(EcoreImport)
   * @see fr.inria.diverse.alex.xtext.alex.AlexPackage#getAlexRoot_EcoreImport()
   * @model containment="true"
   * @generated
   */
  EcoreImport getEcoreImport();

  /**
   * Sets the value of the '{@link fr.inria.diverse.alex.xtext.alex.AlexRoot#getEcoreImport <em>Ecore Import</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ecore Import</em>' containment reference.
   * @see #getEcoreImport()
   * @generated
   */
  void setEcoreImport(EcoreImport value);

  /**
   * Returns the value of the '<em><b>Alex Imports</b></em>' containment reference list.
   * The list contents are of type {@link fr.inria.diverse.alex.xtext.alex.AlexImport}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Alex Imports</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alex Imports</em>' containment reference list.
   * @see fr.inria.diverse.alex.xtext.alex.AlexPackage#getAlexRoot_AlexImports()
   * @model containment="true"
   * @generated
   */
  EList<AlexImport> getAlexImports();

  /**
   * Returns the value of the '<em><b>Classes</b></em>' containment reference list.
   * The list contents are of type {@link fr.inria.diverse.alex.xtext.alex.AlexClass}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Classes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Classes</em>' containment reference list.
   * @see fr.inria.diverse.alex.xtext.alex.AlexPackage#getAlexRoot_Classes()
   * @model containment="true"
   * @generated
   */
  EList<AlexClass> getClasses();

} // AlexRoot
