/**
 * generated by Xtext 2.14.0
 */
package fr.inria.diverse.alex.xtext.alex;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Override Method</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.inria.diverse.alex.xtext.alex.AlexPackage#getOverrideMethod()
 * @model
 * @generated
 */
public interface OverrideMethod extends ConcreteMethod
{
} // OverrideMethod
