/*
 * generated by Xtext 2.14.0
 */
package fr.mleduc.lang.boa.ui;

import com.google.inject.Injector;
import fr.mleduc.lang.boa.ui.internal.BoaActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BoaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(BoaActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		BoaActivator activator = BoaActivator.getInstance();
		return activator != null ? activator.getInjector(BoaActivator.FR_MLEDUC_LANG_BOA_BOA) : null;
	}

}
