/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl4.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyDslScopeProvider extends DelegatingScopeProvider {
}
