/**
 * generated by Xtext 2.14.0
 */
package alex.xtext.alex.impl;

import alex.xtext.alex.AbstractMethod;
import alex.xtext.alex.AlexPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Abstract Method</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AbstractMethodImpl extends AlexMethodImpl implements AbstractMethod
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AbstractMethodImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AlexPackage.Literals.ABSTRACT_METHOD;
  }

} //AbstractMethodImpl
