/**
 * generated by Xtext 2.14.0
 */
package alex.xtext.alex.impl;

import alex.xtext.alex.AlexPackage;
import alex.xtext.alex.DefMethod;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Def Method</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DefMethodImpl extends ConcreteMethodImpl implements DefMethod
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DefMethodImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AlexPackage.Literals.DEF_METHOD;
  }

} //DefMethodImpl
