/*
 * generated by Xtext 2.14.0
 */
package calc.xtext.parser.antlr;

import calc.xtext.parser.antlr.internal.InternalCalcParser;
import calc.xtext.services.CalcGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CalcParser extends AbstractAntlrParser {

	@Inject
	private CalcGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCalcParser createParser(XtextTokenStream stream) {
		return new InternalCalcParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Start";
	}

	public CalcGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CalcGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
