/**
 * generated by Xtext 2.14.0
 */
package alex.xtext.alex;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Method</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see alex.xtext.alex.AlexPackage#getAbstractMethod()
 * @model
 * @generated
 */
public interface AbstractMethod extends AlexMethod
{
} // AbstractMethod
