/**
 * generated by Xtext 2.14.0
 */
package alex.xtext.alex;

import org.eclipse.xtext.xbase.XExpression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Concrete Method</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link alex.xtext.alex.ConcreteMethod#getBlock <em>Block</em>}</li>
 * </ul>
 *
 * @see alex.xtext.alex.AlexPackage#getConcreteMethod()
 * @model
 * @generated
 */
public interface ConcreteMethod extends AlexMethod
{
  /**
   * Returns the value of the '<em><b>Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Block</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Block</em>' containment reference.
   * @see #setBlock(XExpression)
   * @see alex.xtext.alex.AlexPackage#getConcreteMethod_Block()
   * @model containment="true"
   * @generated
   */
  XExpression getBlock();

  /**
   * Sets the value of the '{@link alex.xtext.alex.ConcreteMethod#getBlock <em>Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Block</em>' containment reference.
   * @see #getBlock()
   * @generated
   */
  void setBlock(XExpression value);

} // ConcreteMethod
